---

image: docker:latest

stages:
  - build
  - push

#create something

services:
  - docker:dind
build:
 stage: build
 script:
  - docker build -t send .
  - docker tag send awserv/firefox:14.02
  - docker login -u "awserv" -p "$DOCKER_HUB"
  - docker push awserv/firefox:14.02
 only:
    changes:
     - .gitlab-ci.yml
     - Dockerfile
     - README.md
     - app/*

# stage: conect server_A
push:
  stage: push
  needs: # пока предыщая не вып это не заработает
    - job: build
  script:
    - 'command -v ssh-agent >/dev/null || ( apt- update -y && apt- install openssh-client -y apt install docker.io -y )'
    - eval $(ssh-agent -s)
    - docker version && docker info
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh -o StrictHostKeyChecking=no ubuntu@localhost "docker pull awserv/firefox:14.02 && docker run -p 1443:80 -d awserv/firefox:14.02"
